version: '3.8'

services:
  ccxt-data-fetcher:
    build: .
    volumes:
      - ./service_account.json:/app/service_account.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service_account.json
    command: python update_google_sheets.py
