version: '3.8'

services:
  ccxt-data-fetcher:
    image: crypto-analysis-with-machine-learning-ccxt-data-fetcher
    build: .
    volumes:
      - ./service_account.json:/app/service_account.json:rw
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service_account.json
    # network_mode: crypto-analysis-with-machine-learning_default  # Remove or comment out this line
